### PR TITLE
Swift 3 Update

### PR DESCRIPTION
**Pull request by lightclient**
I haven't tested it thoroughly, but I played with the tutorial app on iOS 10 and it seems to work fine. Hopefully this is good starting point for ElasticTransition's continuous compatibility with Swift 3.

### CODE REVIEW

**Comment by petaire92** [comment]
Not so sure it's working my friend, I have a ton of syntax error in Xcode Beta 6!
capture d ecran 2016-08-22 a 20 42 00

**Comment by c-o-l-o-r** [comment]
Can you walk me through what you did? i just git cloned the repo and it built and ran fine on Xcode beta 5.

**Comment by lightclient** [comment]
@petaire92 can you walk me through what you did? i just git cloned the repo and it built and ran fine on Xcode beta 5.

**Comment by petaire92** [comment]
Mmm I'm at work so I have no access to Xcode but maybe it's because I've launch the demo app to try it ? I've never played with it so I wanted to give it a go but maybe I need to try the pod ?

**Comment by lightclient** [comment]
@petaire92 did you happen to open the .xcodeproj rather than the .xcworkspace?

**Comment by petaire92** [comment]
I'll check tonight, I'll walk you through every step I did. I'm kind of new to github, thats the next thing on my wunderlist to master, so maybe I did something wrong. 

It's the master one and not the 2.1.1 one right ?

**Comment by lightclient** [comment]
@petaire92 no worries! It should be the master repo under my name. Just type this in to terminal when you get a chance: "git clone https://github.com/c-o-l-o-r/ElasticTransition-Swift-3.git" wherever you want the project folder, then open up the .xcworkspace file & let me know if you're still having problems!

**Comment by lkzhao** [comment]
@c-o-l-o-r This is great! Thanks for making this. I will test it today and hopefully get it merged.

**Comment by petaire92** [comment]
Okay ! So.

I did not use the git command because I'm still waiting for my github student account to be approved so I'm using the old way.

I've downloaded this zip :
capture d ecran 2016-08-23 a 19 07 28

Then I'm launching ElasticTransitionExample.xcworkspace :
capture d ecran 2016-08-23 a 19 08 04

And then XCode is giving me this : 
capture d ecran 2016-08-23 a 19 08 44

Those are typical Swift3 errors (I got "Value of type 'Any' has no member 'cgRectValue' " a LOT when converting my app). Unfortunately I'm not familiar with CoreAnimation at all so I can't troubleshoot them all !

Did I do something wrong ?

**Comment by lkzhao** [comment]
@c-o-l-o-r 
I have merged this PR into `swift3` branch. Please check it out.
I also made some changes to make it compile on the latest beta 6.

@petaire92 please follow the README in the `swift3` branch. You will need a different podfile configuration since the dependency `MotionAnimation` framework also need to be in swift 3.

**Comment by lightclient** [comment]
@lkzhao looks great, thanks!

**Pull request closed without merging**
